spring.application.name=demo


server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/food_menu_db
spring.datasource.username=postgres
spring.datasource.password=

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

upload.path=C:/Users/makse/picture/
spring.web.resources.static-locations=classpath:/static/,file:///C:/Users/makse/picture/